### ISSUE TITLE
[Issue] The  main branch of AIMOD2 does not contain the path  diagrams

### ISSUE THREAD

**Issue by wikijm** [darkquasar/AIMOD2#1]
Hi @darkquasar,

First of all, thanks a lot for AIMOD2!

I wanted to inform you that /AIMOD2/diagrams/ folder is missing on the main branch:
![image](https://github.com/darkquasar/AIMOD2/assets/10724809/34ae8230-5b05-45de-b302-d6106e94341f)

This results to a dead link on README.md
![image](https://github.com/darkquasar/AIMOD2/assets/10724809/af017c4e-846a-4b73-b035-7d3485bc0bd6)
![image](https://github.com/darkquasar/AIMOD2/assets/10724809/b7e45d56-db3d-4a1d-85f7-fe593926d5c7)

**Comment by darkquasar** [comment]
Hi @wikijm thanks for your great input and attention to detail!

Regarding this issue, I wonder whether you were seeing an older version of the GitHub repo? The images now point to the right diagrams folder: 

https://github.com/darkquasar/AIMOD2/blob/main/content.en/diagrams/mission-functional-levels.excalidraw.png

![image](https://github.com/darkquasar/AIMOD2/assets/28435534/036b7458-882e-4243-89aa-6b1ca75bdff1)

![image](https://github.com/darkquasar/AIMOD2/assets/28435534/8363e137-e7bb-43cd-b243-189e1c310469)

The README seems to be working fine for me now, though I know the links were broken before.

Would you be able to test again and confirm?

Also bear in mind the newest, most updated version of AIMOD2 is now in the website: https://aimod2.com 

I haven't updated the README to match the contents in the website, which is basically build with HUGO

**Comment by darkquasar** [comment]
Hi @wikijm, I realize that you were actually talking about the last image reference. Thanks for that, PR merged!

Closing this issue as resolved.
