### ISSUE TITLE
[Request] SVG version of diagrams

### ISSUE THREAD

**Issue by wikijm** [darkquasar/AIMOD2#3]
Hi @darkquasar

Would it be possible to share SVG version of diagrams instead of PNG?
I'm asking regarding https://github.com/darkquasar/AIMOD2/issues/2, also because I like to have "stretchable" images to integrate them no matter the document/device I'm using.

Thanks!

**Comment by darkquasar** [comment]
This is actually a great idea, I should have uploaded the SVG versions from the beginning. I have now replaced all diagrams with the SVG version, would you be able to do some spot-checks and confirm?

Thanks again for the thorough reading and feedback.

**Comment by wikijm** [comment]
This is perfect, thanks a lot!
Have a lovely weekend 😃
